-- SYS 관리자 계정
ALTER SESSION SET"_ORACLE_SCRIPT"=TRUE;

-- 사용자 계정 생성
CREATE USER em_lyh IDENTIFIED BY em1234;

-- 생성한 사용자 계정에 권한 부여
GRANT CONNECT, RESOURCE, CREATE VIEW TO em_lyh;

-- 테이블 스페이스 할당
ALTER USER em_lyh DEFAULT
TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

------------------------------------------------------------------


-- em_lyh 계정

-- 회원 테이블
-- 회원 번호, 아이디, 비밀번호, 이름, 성별, 가입일, 탈퇴여부
CREATE TABLE "MEMBER"(
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(30) NOT NULL,
	MEMBER_PW VARCHAR2(30) NOT NULL,
	MEMBER_NM VARCHAR2(30) NOT NULL,
	MEMBER_GENDER CHAR(1) CHECK( MEMBER_GENDER IN ('M', 'F'	)),
	ENROLL_DATE DATE DEFAULT SYSDATE, 
	SECESSION_FL CHAR(1) DEFAULT 'N' CHECK( SECESSION_FL IN ('Y','N')),
	SELLER_RIGHT CHAR(1) DEFAULT 'N' CHECK( SELLER_RIGHT IN ('Y','N'))
);

COMMENT ON COLUMN "MEMBER".MEMBER_NO IS '회원번호';
COMMENT ON COLUMN "MEMBER".MEMBER_ID IS '회원 아이디';
COMMENT ON COLUMN "MEMBER".MEMBER_PW IS '회원 비밀번호';
COMMENT ON COLUMN "MEMBER".MEMBER_NM IS '회원 이름';
COMMENT ON COLUMN "MEMBER".MEMBER_GENDER IS '회원 성별';
COMMENT ON COLUMN "MEMBER".ENROLL_DATE IS '회원 가입일';
COMMENT ON COLUMN "MEMBER".SECESSION_FL IS '탈퇴여부(Y/N)';
COMMENT ON COLUMN "MEMBER".SELLER_RIGHT IS '판매자 권한';

-- 문자열보다 숫자열 비교속도가 빠르다 PRIMARY는 NUMBER가 더 좋다

-- 회원 번호 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO 
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE; -- CAHHE(20)저장 안하고 끄면 다음 실행 시 21부터 시작해 NOCACHE 설정

-- 회원 가입 INSERT 
INSERT INTO "MEMBER" 
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user01', 'pass01','유저일', 'M', DEFAULT, DEFAULT, DEFAULT	);

INSERT INTO "MEMBER" 
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user02', 'pass02','유저이', 'F', DEFAULT, DEFAULT, DEFAULT	);

INSERT INTO "MEMBER" 
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user03', 'pass03','유저삼', 'F', DEFAULT, DEFAULT, 'Y'	);

SELECT * FROM MEMBER;

COMMIT;

---------------------------------------------------------

CREATE TABLE GOODS(
	GOODS_NO NUMBER PRIMARY KEY,
	GOODS_NM VARCHAR2(500) NOT NULL,
	GOODS_PRICE NUMBER NOT NULL,
	GOODS_CONTENT VARCHAR2(4000) NOT NULL,
	ENROLL_DT DATE DEFAULT SYSDATE,
	READ_COUNT NUMBER DEFAULT 0,
	DELETE_FL CHAR(1) DEFAULT 'N' CHECK(DELETE_FL IN ('N','Y')),
	MEMBER_NO NUMBER REFERENCES MEMBER
);

COMMENT ON COLUMN GOODS.GOODS_NO IS '등록 번호';
COMMENT ON COLUMN GOODS.GOODS_NM IS '이름';
COMMENT ON COLUMN GOODS.GOODS_PRICE IS '가격';
COMMENT ON COLUMN GOODS.GOODS_CONTENT IS '상품 설명';
COMMENT ON COLUMN GOODS.ENROLL_DT IS '등록일';
COMMENT ON COLUMN GOODS.READ_COUNT IS '조회수';
COMMENT ON COLUMN GOODS.DELETE_FL IS '게시글 삭제여부';
COMMENT ON COLUMN GOODS.MEMBER_NO IS '판매자 회원번호';

-- 게시판 번호 시퀀스
CREATE SEQUENCE SEQ_GOODS_NO NOCACHE;

-- 게시판 샘플 데이터
SELECT*FROM MEMBER WHERE SECESSION_FL='N';

INSERT INTO GOODS
VALUES(SEQ_GOODS_NO.NEXTVAL, '가위', '1000','잘 잘리는 가위입니다',
		TO_DATE('2022-09-20 10:30:12', 'YYYY-MM-DD HH24:MI:SS'),
		DEFAULT, DEFAULT, 1);

------------------------------------------------------------------
	
CREATE TABLE "COMMENT"(
	COMMENT_NO NUMBER,
	COMMENT_CONTENT VARCHAR2(900) NOT NULL,
	CREATE_DT DATE DEFAULT SYSDATE,
	DELETE_FL CHAR(1) DEFAULT 'N' CHECK(DELETE_FL IN('N','Y')),
	MEMBER_NO NUMBER REFERENCES MEMBER,
	GOODS_NO NUMBER REFERENCES GOODS,
	CONSTRAINT COMMENT_PK PRIMARY KEY(COMMENT_NO)
); 

COMMENT ON COLUMN "COMMENT".COMMENT_NO IS '댓글 번호';
COMMENT ON COLUMN "COMMENT".COMMENT_CONTENT IS '댓글 내용';
COMMENT ON COLUMN "COMMENT".CREATE_DT IS '댓글 작성일';
COMMENT ON COLUMN "COMMENT".DELETE_FL IS '댓글 삭제 여부';
COMMENT ON COLUMN "COMMENT".MEMBER_NO IS '댓글 작성자 회원 번호';
COMMENT ON COLUMN "COMMENT".GOODS_NO IS '댓글 작성된 상품 번호';

COMMIT;

-- 댓글 번호 시퀀스 생성
CREATE SEQUENCE SEQ_COMMENT_NO NOCACHE;

-- 댓글 샘플 데이터 삽입
INSERT INTO "COMMENT"
VALUES(SEQ_COMMENT_NO.NEXTVAL, '댓글 샘플 1번', DEFAULT, DEFAULT, 3, 3);
INSERT INTO "COMMENT"
VALUES(SEQ_COMMENT_NO.NEXTVAL, '댓글 샘플 2번', DEFAULT, DEFAULT, 3, 3);
INSERT INTO "COMMENT"
VALUES(SEQ_COMMENT_NO.NEXTVAL, '댓글 샘플 3번', DEFAULT, DEFAULT, 3, 3);	
	
	
	
	
	
	
	
	
	
	
------------------------------------------------------------------
CREATE TABLE MANAGER (
	MANAGER_NO NUMBER PRIMARY KEY,
	MANAGER_ID VARCHAR2(30) NOT NULL,
	MANAGER_PW VARCHAR2(30) NOT NULL,
	MANAGER_NM VARCHAR2(30) NOT NULL,
	MANAGER_GENDER CHAR(1) CHECK( MANAGER_GENDER IN ('M', 'F')),
	ENROLL_DATE DATE DEFAULT SYSDATE, 
	SECESSION_FL CHAR(1) DEFAULT 'N' CHECK( SECESSION_FL IN ('Y','N'))
);

COMMENT ON COLUMN MANAGER.MANAGER_NO IS '관리자번호';
COMMENT ON COLUMN MANAGER.MANAGER_ID IS '관리자 아이디';
COMMENT ON COLUMN MANAGER.MANAGER_PW IS '관리자 비밀번호';
COMMENT ON COLUMN MANAGER.MANAGER_NM IS '관리자 이름';
COMMENT ON COLUMN MANAGER.MANAGER_GENDER IS '관리자 성별';
COMMENT ON COLUMN MANAGER.ENROLL_DATE IS '관리자 가입일';
COMMENT ON COLUMN MANAGER.SECESSION_FL IS '탈퇴여부(Y/N)';

CREATE SEQUENCE SEQ_MANAGER_NO NOCACHE;

INSERT INTO MANAGER 
VALUES(SEQ_MANAGER_NO.NEXTVAL, 'manager01', 'pass01','관리일', 'M', DEFAULT, DEFAULT);

COMMIT;
-----------------------------------------------------------------------
CREATE TABLE SR_BOARD(
	SR_BOARD_NO NUMBER PRIMARY KEY,
	MEMBER_NO NUMBER REFERENCES MEMBER
);



COMMENT ON COLUMN SR_BOARD.SR_BOARD_NO IS '판매권리 신청번호';
COMMENT ON COLUMN SR_BOARD.MEMBER_N0 IS '신청자 회원번호';

CREATE SEQUENCE SEQ_SR_BOARD_NO NOCACHE;

SELECT*FROM MEMBER;
----------------------------------------------------------------------
