-- SYS 관리자 계정
ALTER SESSION SET"_ORACLE_SCRIPT"=TRUE;

-- 사용자 계정 생성
CREATE USER em_lyh IDENTIFIED BY em1234;

-- 생성한 사용자 계정에 권한 부여
GRANT CONNECT, RESOURCE, CREATE VIEW TO em_lyh;

-- 테이블 스페이스 할당
ALTER USER em_lyh DEFAULT
TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

------------------------------------------------------------------


-- em_lyh 계정

-- 회원 테이블
-- 회원 번호, 아이디, 비밀번호, 이름, 성별, 가입일, 탈퇴여부
CREATE TABLE "MEMBER"(
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(30) NOT NULL,
	MEMBER_PW VARCHAR2(30) NOT NULL,
	MEMBER_NM VARCHAR2(30) NOT NULL,
	MEMBER_GENDER CHAR(1) CHECK( MEMBER_GENDER IN ('M', 'F'	)),
	ENROLL_DATE DATE DEFAULT SYSDATE, 
	SECESSION_FL CHAR(1) DEFAULT 'N' CHECK( SECESSION_FL IN ('Y','N'))
);

COMMENT ON COLUMN "MEMBER".MEMBER_NO IS '회원번호';
COMMENT ON COLUMN "MEMBER".MEMBER_ID IS '회원 아이디';
COMMENT ON COLUMN "MEMBER".MEMBER_PW IS '회원 비밀번호';
COMMENT ON COLUMN "MEMBER".MEMBER_NM IS '회원 이름';
COMMENT ON COLUMN "MEMBER".MEMBER_GENDER IS '회원 성별';
COMMENT ON COLUMN "MEMBER".MEMBER_DATE IS '회원 가입일';
COMMENT ON COLUMN "MEMBER".SECESSION_FL IS '탈퇴여부(Y/N)';

-- 문자열보다 숫자열 비교속도가 빠르다 PRIMARY는 NUMBER가 더 좋다

-- 회원 번호 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO 
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE; -- CAHHE(20)저장 안하고 끄면 다음 실행 시 21부터 시작해 NOCACHE 설정

-- 회원 가입 INSERT 
INSERT INTO "MEMBER" 
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user01', 'pass01','유저일', 'M', DEFAULT, DEFAULT	);

INSERT INTO "MEMBER" 
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user02', 'pass02','유저이', 'F', DEFAULT, DEFAULT	);

INSERT INTO "MEMBER" 
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user03', 'pass03','유저삼', 'F', DEFAULT, DEFAULT	);

SELECT * FROM MEMBER;

--------------------------------------------------------------------------

-- 판매자 테이블
-- 판매자 번호, 아이디, 비번, 상호, 계좌번호, 가입일, 탈퇴여부
CREATE TABLE SELLER(
	SELLER_NO NUMBER PRIMARY KEY,
	SELLER_ID VARCHAR2(30) NOT NULL,
	SELLER_PW VARCHAR2(30) NOT NULL,
	BUSINESS_NM VARCHAR2(30) NOT NULL,
	ACCOUNT VARCHAR2(30) NOT NULL,
	ENROLL_DATE DATE DEFAULT SYSDATE, 
	SECESSION_FL CHAR(1) DEFAULT 'N' CHECK( SECESSION_FL IN ('Y','N'))
);


COMMENT ON COLUMN SELLER.SELLER_NO IS '판매자 번호';
COMMENT ON COLUMN SELLER.SELLER_ID IS '판매자 아이디';
COMMENT ON COLUMN SELLER.SELLER_PW IS '판매자 비밀번호';
COMMENT ON COLUMN SELLER.BUSINESS_NM IS '상호';
COMMENT ON COLUMN SELLER.ACCOUNT IS '계좌번호';
COMMENT ON COLUMN SELLER.ENROLL_DATE IS '판매자 가입일';
COMMENT ON COLUMN SELLER.SECESSION_FL IS '탈퇴여부';

-- 회원 번호 시퀀스 생성
CREATE SEQUENCE SEQ_SELLER_NO 
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE; -- CAHHE(20)저장 안하고 끄면 다음 실행 시 21부터 시작해 NOCACHE 설정

-- 회원 가입 INSERT 
INSERT INTO SELLER 
VALUES(SEQ_SELLER_NO.NEXTVAL, 'seller01', 'pass01', 'a사', '12341234123412', DEFAULT, DEFAULT	);

INSERT INTO SELLER 
VALUES(SEQ_SELLER_NO.NEXTVAL, 'seller02', 'pass02', 'b사',	 '43214321432143', DEFAULT, DEFAULT	);

INSERT INTO SELLER 
VALUES(SEQ_SELLER_NO.NEXTVAL, 'seller03', 'pass03', 'c사',	 '56785678567856', DEFAULT, DEFAULT	);

SELECT*FROM SELLER;
------------------------------------------------------


